name: github-insight-test

on:
  push:
    branches: 
      - main
      - test
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: github-insight-test
    steps:
      - uses: actions/checkout@v3
      - uses: HeesuKim0203/github-insight@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
